version: '3'
services: 
    envoygateway:
        build: Envoy/
        ports:
            - "9901:9901"
            - "10000:10000"
        volumes:
            - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
    coffeeapi:
        build: CoffeeAPI/
        ports: 
            - "8085:80"
            - "8086:443"
        environment: 
            ASPNETCORE_URLS: "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: "8086"
            ASPNETCORE_ENVIRONMENT: "Development"
        volumes:
            - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
            - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
            
    teaapi:
        build: TeaAPI/
        ports: 
            - "8087:80"
            - "8088:443"
        environment: 
            ASPNETCORE_URLS: "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: "8088"
            ASPNETCORE_ENVIRONMENT: "Development"
        volumes:
            - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
            - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
            